app:
  name: "Cedar (Dev)"
  title: "Cedar Development"
  description: "Your AI Assistant - Development Mode"

ai:
  assistant_name: "Cedar Dev Assistant"
  system_message: "You are a helpful AI assistant running in development mode. You provide clear, logical, and well-reasoned responses to user questions and requests. You are knowledgeable across many domains and can help with a wide variety of tasks. Debug information may be more verbose in this mode."

providers:
  deepinfra:
    models:
      Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo:
        name: Qwen3 Coder
        thinking: true
      Qwen/Qwen3-235B-A22B-Instruct-2507:
        name: Qwen3 235B A22B
      moonshotai/Kimi-K2-Instruct-0905:
        name: Kimi K2
      deepseek-ai/DeepSeek-V3.1:
        name: DeepSeek V3.1
      openai/gpt-oss-120b:
        name: GPT OSS 120B
        thinking: true
      zai-org/GLM-4.5-Air:
        name: GLM-4.5 Air
        thinking: true
      meta-llama/Llama-3.3-70B-Instruct-Turbo:
        name: Llama 3.3 70B Instruct Turbo
      mistralai/Mistral-Small-3.2-24B-Instruct-2506:
        name: Mistral Small 3.2
  openrouter:
    models:
      openai/gpt-5:
        name: "GPT-5"
        reasoning: true
      openai/gpt-5-mini:
        name: "GPT-5 Mini"
        reasoning: true
      openai/gpt-5-nano:
        name: "GPT-5 Nano"
        reasoning: true
      openai/gpt-oss-20b:
        name: "GPT-OSS 20B"
        reasoning: true
      openai/gpt-oss-120b:
        name: "GPT-OSS 120B"
        reasoning: true
      anthropic/claude-opus-4.1:
        name: "Claude Opus 4.1"
      anthropic/claude-sonnet-4:
        name: "Claude Sonnet 4"
      anthropic/claude-3.5-haiku:
        name: "Claude 3.5 Haiku"
      google/gemini-2.5-pro:
        name: "Gemini 2.5 Pro"
      google/gemini-2.5-flash:
        name: "Gemini 2.5 Flash"
      google/gemini-2.5-flash-lite:
        name: "Gemini 2.5 Flash Lite"
      google/gemma-3-27b-it:
        name: "Gemma 3 27B"
      deepseek/deepseek-r1-0528:
        name: "DeepSeek R1 0528"
        reasoning: true
      deepseek/deepseek-r1-0528-qwen3-8b:
        name: "DeepSeek R1 Qwen 8B"
        reasoning: true
      deepseek/deepseek-chat-v3.1:
        name: "DeepSeek Chat V3.1"
      moonshotai/kimi-k2:
        name: "Kimi K2"
        reasoning: true
      meta-llama/llama-4-maverick:
        name: "Llama 4 Maverick"
      meta-llama/llama-4-scout:
        name: "Llama 4 Scout"
      meta-llama/llama-3.3-70b-instruct:
        name: "Llama 3.3 70B"
      qwen/qwen3-235b-a22b-2507:
        name: "Qwen3 235B A22B"
      qwen/qwen3-235b-a22b-thinking-2507:
        name: "Qwen3 235B A22B Thinking"
        reasoning: true
      qwen/qwen3-30b-a3b:
        name: "Qwen3 30B A3B"
        reasoning: true
      qwen/qwen3-coder:
        name: "Qwen3 Coder"
        reasoning: true
      mistralai/mistral-small-3.2-24b-instruct:
        name: "Mistral Small 3.2 24B"
      mistralai/magistral-small-2506:
        name: "Magistral Small 3.2 24B"
        reasoning: true
      x-ai/grok-4:
        name: "Grok 4"
        reasoning: true
      x-ai/grok-code-fast-1:
        name: "Grok Code Fast 1"
        reasoning: true
      perplexity/r1-1776:
        name: "Perplexity R1 1776"
        reasoning: true
      perplexity/sonar-reasoning-pro:
        name: "Sonar Reasoning Pro"
        reasoning: true
      perplexity/sonar-reasoning:
        name: "Sonar Reasoning"
        reasoning: true
      perplexity/sonar-pro:
        name: "Sonar Pro"
      perplexity/sonar:
        name: "Sonar"

models:
  temperature: 0.1 # Lower temperature for more consistent dev testing
  max_tokens: 4096 # Higher token limit for development
