app:
  name: "Cedar"
  title: "Cedar" 
  description: "Your AI Assistant"

ai:
  assistant_name: "Cedar Assistant"
  system_message: "You are a helpful AI assistant. You provide clear, logical, and well-reasoned responses to user questions and requests. You are knowledgeable across many domains and can help with a wide variety of tasks."

models:
  default: "google/gemini-2.5-flash"
  temperature: 0.3
  max_tokens: 2048
  title_generation: "openai/gpt-oss-20b"
  mappings:
    auto: "openrouter/auto"
    smart: "google/gemini-2.5-flash"
    creative: "moonshotai/kimi-k2"
    fast: "google/gemini-2.5-flash-lite"
    reasoning: "openai/gpt-oss-120b"

ui:
  chat_placeholder: "Type your message..."
  max_history_items: 50
  default_chat_name: "New chat"

features:
  enable_dev_models: false
  enable_reasoning_display: true
  enable_model_selection: true
  enable_debug_logging: false
