/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestingImport } from './routes/testing'
import { Route as ChatsImport } from './routes/chats'
import { Route as IndexImport } from './routes/index'
import { Route as ChatThreadTokenImport } from './routes/chat.$threadToken'

// Create/Update Routes

const TestingRoute = TestingImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRoute,
} as any)

const ChatsRoute = ChatsImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChatThreadTokenRoute = ChatThreadTokenImport.update({
  id: '/chat/$threadToken',
  path: '/chat/$threadToken',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsImport
      parentRoute: typeof rootRoute
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingImport
      parentRoute: typeof rootRoute
    }
    '/chat/$threadToken': {
      id: '/chat/$threadToken'
      path: '/chat/$threadToken'
      fullPath: '/chat/$threadToken'
      preLoaderRoute: typeof ChatThreadTokenImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/testing': typeof TestingRoute
  '/chat/$threadToken': typeof ChatThreadTokenRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/testing': typeof TestingRoute
  '/chat/$threadToken': typeof ChatThreadTokenRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/testing': typeof TestingRoute
  '/chat/$threadToken': typeof ChatThreadTokenRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chats' | '/testing' | '/chat/$threadToken'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chats' | '/testing' | '/chat/$threadToken'
  id: '__root__' | '/' | '/chats' | '/testing' | '/chat/$threadToken'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  TestingRoute: typeof TestingRoute
  ChatThreadTokenRoute: typeof ChatThreadTokenRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  TestingRoute: TestingRoute,
  ChatThreadTokenRoute: ChatThreadTokenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chats",
        "/testing",
        "/chat/$threadToken"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chats": {
      "filePath": "chats.tsx"
    },
    "/testing": {
      "filePath": "testing.tsx"
    },
    "/chat/$threadToken": {
      "filePath": "chat.$threadToken.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
